In [27]:
import cv2
import numpy as np
import glob

In [28]:
chessboard_size = (9,6)
obj_points = np.zeros((np.prod(chessboard_size), 3), dtype=np.float32)
obj_points[:, :2] = np.indices(chessboard_size).T.reshape(-1, 2)
print(obj_points)

[[0. 0. 0.]
 [1. 0. 0.]
 [2. 0. 0.]
 [3. 0. 0.]
 [4. 0. 0.]
 [5. 0. 0.]
 [6. 0. 0.]
 [7. 0. 0.]
 [8. 0. 0.]
 [0. 1. 0.]
 [1. 1. 0.]
 [2. 1. 0.]
 [3. 1. 0.]
 [4. 1. 0.]
 [5. 1. 0.]
 [6. 1. 0.]
 [7. 1. 0.]
 [8. 1. 0.]
 [0. 2. 0.]
 [1. 2. 0.]
 [2. 2. 0.]
 [3. 2. 0.]
 [4. 2. 0.]
 [5. 2. 0.]
 [6. 2. 0.]
 [7. 2. 0.]
 [8. 2. 0.]
 [0. 3. 0.]
 [1. 3. 0.]
 [2. 3. 0.]
 [3. 3. 0.]
 [4. 3. 0.]
 [5. 3. 0.]
 [6. 3. 0.]
 [7. 3. 0.]
 [8. 3. 0.]
 [0. 4. 0.]
 [1. 4. 0.]
 [2. 4. 0.]
 [3. 4. 0.]
 [4. 4. 0.]
 [5. 4. 0.]
 [6. 4. 0.]
 [7. 4. 0.]
 [8. 4. 0.]
 [0. 5. 0.]
 [1. 5. 0.]
 [2. 5. 0.]
 [3. 5. 0.]
 [4. 5. 0.]
 [5. 5. 0.]
 [6. 5. 0.]
 [7. 5. 0.]
 [8. 5. 0.]]


In [29]:
object_points = []
image_points =[]
images = glob.glob('photos/*.jpg')
if len(images) < 8:
    print("请确保有至少8张棋盘格图像")
else:
    images = images[:8]  
print(images)

['photos\\photo1.jpg', 'photos\\photo2.jpg', 'photos\\photo3.jpg', 'photos\\photo4.jpg', 'photos\\photo5.jpg', 'photos\\photo6.jpg', 'photos\\photo7.jpg', 'photos\\photo8.jpg']


In [30]:
for image_path in images:
    img = cv2.imread(image_path)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    ret, corners = cv2.findChessboardCorners(gray, chessboard_size, None)
    
    if ret:
        object_points.append(obj_points)  
        image_points.append(corners)      
        
        cv2.drawChessboardCorners(img, chessboard_size, corners, ret)
        cv2.imshow('Chessboard', img)
        cv2.waitKey(500)  
cv2.destroyAllWindows()

In [31]:
if len(object_points) == 0:
    print('没有有效角点图像')
else:
    ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(object_points, image_points, gray.shape[::-1], None, None)

    print("相机内参矩阵：\n", mtx)
    print("畸变系数：\n", dist)
    print("旋转向量：\n", rvecs)
    print("平移向量：\n", tvecs)
np.savez("camera_calibration.npz", mtx=mtx, dist=dist, rvecs=rvecs, tvecs=tvecs)

相机内参矩阵：
 [[509.68381159   0.         863.29147178]
 [  0.         509.83967968 596.07031206]
 [  0.           0.           1.        ]]
畸变系数：
 [[ 0.0297078  -0.03153182 -0.00058031  0.00045988  0.00826747]]
旋转向量：
 (array([[-0.03381634],
       [ 0.06408721],
       [ 3.13125972]]),)
平移向量：
 (array([[3.96491216],
       [2.0231918 ],
       [3.64069924]]),)
